**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: Alejandra Edith Tobias Villa
*   MATRÍCULA: A01840886

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [1]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 2.5 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [2]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd
from datetime import date

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [3]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC5053User:mnaTC5053Pass!@20.127.169.219:3306/Netflix', pool_recycle=3600)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae toda la información de las películas que duran más de 5 horas.

In [4]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE runtime > 5*60
""")
pd.read_sql(query, conn)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [5]:
query = sqla.text("""
  SELECT
    AVG(available_globally = FALSE) * 100 AS Porcentaje
FROM movie
WHERE available_globally IS NOT NULL;
""")
pd.read_sql(query, conn)

   Porcentaje
0     83.5717

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas? EN - Inglés
* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python) 11255

In [6]:
query = sqla.text("""
  SELECT locale,
    COUNT(*)
  FROM movie
  GROUP BY locale
""")
pd.read_sql(query, conn)

  locale  COUNT(*)
0   None     11255
1     en       532

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* **Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).**
3947

*  **¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes. **

    No coinciden los resultados. Cantidad de títulos diferentes son 3947, mientras que los nulos son 11255.

    Los títulos restantes si son diferentes pero solo por diferencias en caracteres que usan los idiomas/regiones originales, por lo que la consulta los detecta como iguales.

* **Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.** Basandome en los datos, la suposición es correcta. Se hizo un query adicional para confirmar que los datos locale nulos contengan títulos distintos.

In [7]:
query = sqla.text("""
  SELECT
    COUNT(*) AS Titulos_Diferentes
  FROM movie
  WHERE title != original_title
""")
pd.read_sql(query, conn)

   Titulos_Diferentes
0                3947

In [8]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE title = original_title and locale is null
""")
pd.read_sql(query, conn)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,1089,2024-01-01,2024-01-01,b'\x00',None,Recep İvedik 7,None,133,Recep Ivedik 7
1,1349,2024-01-01,2024-01-01,b'\x00',None,Verónica,None,105,Veronica
2,3509,2024-01-01,2024-01-01,b'\x00',None,Fantômas,None,100,Fantomas
3,3611,2024-01-01,2024-01-01,b'\x00',None,Luccas Neto em: O Hotel Mágico,None,70,Luccas Neto em: O Hotel Magico
4,4566,2024-01-01,2024-01-01,b'\x00',None,Un día en el paraíso,None,97,Un Dia En El Paraiso
5,5077,2024-01-01,2024-01-01,b'\x01',None,Superlópez,None,108,Superlopez
6,5211,2024-01-01,2024-01-01,b'\x00',None,Barış Akarsu Merhaba,None,115,Baris Akarsu Merhaba
7,5684,2024-01-01,2024-01-01,b'\x00',None,Tótem,None,95,Totem
8,6427,2024-01-01,2024-01-01,b'\x01',None,La pena máxima,None,89,La Pena Maxima
9,6530,2024-01-01,2024-01-01,b'\x00',None,Mirciulică,None,92,Mirciulica
10,7205,2024-01-01,2024-01-01,b'\x00',None,Ánimas,2019-01-25,87,Animas
11,7519,2024-01-01,2024-01-01,b'\x00',None,Déjame Vivir,None,62,Dejame Vivir
12,7726,2024-01-01,2024-01-01,b'\x00',None,Gangster Ka: Afričan,None,97,Gangster Ka: African
13,8459,2024-01-01,2024-01-01,b'\x00',None,Párty Hárd,None,62,Party Hard
14,10358,2024-01-01,2024-01-01,b'\x00',None,Éxtasis,None,88,Extasis
15,10592,2024-01-01,2024-01-01,b'\x00',None,Maléfique,None,86,Malefique
16,11031,2024-01-01,2024-01-01,b'\x00',None,Tiramisù,None,92,Tiramisu

In [9]:
query = sqla.text("""
  SELECT *
  FROM movie
  WHERE title != original_title and locale is null
""")
pd.read_sql(query, conn)

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,3,2024-01-01,2024-01-01,b'\x01',None,La sociedad de la nieve,2024-01-04,146,Society of the Snow
1,4,2024-01-01,2024-01-01,b'\x01',None,Sous la Seine,2024-06-05,104,Under Paris
2,17,2024-01-01,2024-01-01,b'\x01',None,황야,2024-01-26,109,Badland Hunters
3,20,2024-01-01,2024-01-01,b'\x01',None,Fabbricante di lacrime,2024-04-04,105,The Tearsmith
4,22,2024-01-01,2024-01-01,b'\x00',None,Avgrunden,2024-02-16,103,The Abyss
...,...,...,...,...,...,...,...,...,...
3942,11101,2024-01-01,2024-01-01,b'\x00',None,괴물들,None,102,Wretches
3943,11102,2024-01-01,2024-01-01,b'\x01',None,노란문: 세기말 시네필 다이어리,2023-10-27,85,Yellow Door: '90s Lo-fi Film Club
3944,11103,2024-01-01,2024-01-01,b'\x00',None,那些年，我們一起追的女孩,None,110,You Are the Apple of My Eye
3945,11104,2024-01-01,2024-01-01,b'\x01',None,Sen Benim HerŞeyimsin,None,107,You're Everything To Me
3946,11105,2024-01-01,2024-01-01,b'\x00',None,Operation Ragnarok,None,89,Zone 261

5.	Determina el título de la película que ha permanecido más tiempo en el top 10. The Boss Baby

In [10]:
query = sqla.text("""
SELECT
    m.id,
    v.movie_id,
    m.title,
    v.view_rank,
    v.cumulative_weeks_in_top10,
    v.duration,
    v.start_date,
    v.end_date
FROM view_summary v
INNER JOIN movie m ON m.id = v.movie_id
WHERE v.view_rank BETWEEN 1 AND 10
  AND v.view_rank IS NOT NULL
ORDER BY v.cumulative_weeks_in_top10 DESC
LIMIT 1
""")
pd.read_sql(query, conn)

,id,movie_id,title,view_rank,cumulative_weeks_in_top10,duration,start_date,end_date
0,11197,11197,The Boss Baby,10,22,WEEKLY,2025-07-14,2025-07-20

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [11]:
query = sqla.text("""
SELECT t.title,
    max(season_number) AS Max_season_number
FROM season s
INNER JOIN tv_show t on t.id = s.tv_show_id
GROUP BY (t.title)
ORDER BY Max_season_number desc
LIMIT 5
""")
pd.read_sql(query, conn)

                                               title  Max_season_number
0        Gen Hoshino Concert Recollections 2015-2023           20152023
1  How do you like Wednesday?: Entry into the Arc...            6201998
2       How do you like Wednesday?: Mission complete             202007
3                                        Cocaine Air              30000
4                                 A Tragedy Foretold               3054

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [12]:
query = sqla.text("""
SELECT
  start_date,
  end_date,
  DATEDIFF(end_date, start_date) AS intervalo
FROM view_summary
WHERE duration = 'SEMI_ANNUALLY'
""")
pd.read_sql(query, conn)

       start_date    end_date  intervalo
0      2024-01-01  2024-06-30        181
1      2024-01-01  2024-06-30        181
2      2024-01-01  2024-06-30        181
3      2024-01-01  2024-06-30        181
4      2024-01-01  2024-06-30        181
...           ...         ...        ...
31670  2023-07-01  2023-12-31        183
31671  2023-07-01  2023-12-31        183
31672  2023-07-01  2023-12-31        183
31673  2023-07-01  2023-12-31        183
31674  2023-07-01  2023-12-31        183

[31675 rows x 3 columns]

In [13]:
query = sqla.text("""
SELECT
  MIN(start_date),
  MAX(end_date)
FROM view_summary
WHERE duration = 'SEMI_ANNUALLY'
""")
pd.read_sql(query, conn)

  MIN(start_date) MAX(end_date)
0      2023-07-01    2024-06-30

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

La temporada con más vistas en el primer periodo semestral de 2024 fue la 1. De acuerdo a los datos, la cantidad de vistas fue reduciendo conforme avanzaban las temporadas.

In [14]:
query = sqla.text("""
SELECT
  t.created_date,
  s.season_number,
  s.title,
  v.views,
  v.start_date,
  v.end_date
FROM tv_show t
JOIN season s on t.id = s.tv_show_id
JOIN view_summary v on s.id = v.season_id
WHERE t.title = "Grey's Anatomy" and v.end_date between '2024-01-01' AND '2024-06-30'
ORDER BY views desc
""")
pd.read_sql(query, conn)

,created_date,season_number,title,views,start_date,end_date
0,2024-01-01,1,Grey's Anatomy: Season 1,3600000,2024-01-01,2024-06-30
1,2024-01-01,2,Grey's Anatomy: Season 2,3100000,2024-01-01,2024-06-30
2,2024-01-01,3,Grey's Anatomy: Season 3,2900000,2024-01-01,2024-06-30
3,2024-01-01,5,Grey's Anatomy: Season 5,2900000,2024-01-01,2024-06-30
4,2024-01-01,4,Grey's Anatomy: Season 4,2900000,2024-01-01,2024-06-30
5,2024-01-01,6,Grey's Anatomy: Season 6,2800000,2024-01-01,2024-06-30
6,2024-01-01,7,Grey's Anatomy: Season 7,2700000,2024-01-01,2024-06-30
7,2024-01-01,8,Grey's Anatomy: Season 8,2600000,2024-01-01,2024-06-30
8,2024-01-01,9,Grey's Anatomy: Season 9,2500000,2024-01-01,2024-06-30
9,2024-01-01,10,Grey's Anatomy: Season 10,2400000,2024-01-01,2024-06-30
10,2024-01-01,11,Grey's Anatomy: Season 11,2200000,2024-01-01,2024-06-30
11,2024-01-01,12,Grey's Anatomy: Season 12,2000000,2024-01-01,2024-06-30
12,2024-01-01,13,Grey's Anatomy: Season 13,2000000,2024-01-01,2024-06-30
13,2024-01-01,14,Grey's Anatomy: Season 14,2000000,2024-01-01,2024-06-30
14,2024-01-01,19,Grey's Anatomy: Season 19,2000000,2024-01-01,2024-06-30
15,2024-01-01,15,Grey's Anatomy: Season 15,1900000,2024-01-01,2024-06-30
16,2024-01-01,16,Grey's Anatomy: Season 16,1800000,2024-01-01,2024-06-30
17,2024-01-01,18,Grey's Anatomy: Season 18,1700000,2024-01-01,2024-06-30
18,2024-01-01,17,Grey's Anatomy: Season 17,1700000,2024-01-01,2024-06-30
19,2024-01-01,20,Grey's Anatomy: Season 20,100000,2024-01-01,2024-06-30

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [15]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [16]:
result = (
    tv_show
    .merge(
        season,
        left_on='id',
        right_on='tv_show_id'
    )
    .merge(
        view_summary,
        left_on='id_y',
        right_on='season_id'
    )
)

result = result[
    (result['title_x'] == "Grey's Anatomy") &
    (result['end_date'].between(
        date(2024, 1, 1),
        date(2024, 6, 30)
    ))
]

result = result.rename(columns={'title_y': 'season_title'})

result[
    [
        'season_number',
        'season_title',
        'views',
        'start_date',
        'end_date'
    ]
].sort_values(by='views', ascending=False)

,season_number,season_title,views,start_date,end_date
2309,1.0,Grey's Anatomy: Season 1,3600000,2024-01-01,2024-06-30
2311,2.0,Grey's Anatomy: Season 2,3100000,2024-01-01,2024-06-30
2313,3.0,Grey's Anatomy: Season 3,2900000,2024-01-01,2024-06-30
2315,5.0,Grey's Anatomy: Season 5,2900000,2024-01-01,2024-06-30
2317,4.0,Grey's Anatomy: Season 4,2900000,2024-01-01,2024-06-30
2319,6.0,Grey's Anatomy: Season 6,2800000,2024-01-01,2024-06-30
2321,7.0,Grey's Anatomy: Season 7,2700000,2024-01-01,2024-06-30
2323,8.0,Grey's Anatomy: Season 8,2600000,2024-01-01,2024-06-30
2325,9.0,Grey's Anatomy: Season 9,2500000,2024-01-01,2024-06-30
2327,10.0,Grey's Anatomy: Season 10,2400000,2024-01-01,2024-06-30
2329,11.0,Grey's Anatomy: Season 11,2200000,2024-01-01,2024-06-30
2331,12.0,Grey's Anatomy: Season 12,2000000,2024-01-01,2024-06-30
2333,13.0,Grey's Anatomy: Season 13,2000000,2024-01-01,2024-06-30
2335,14.0,Grey's Anatomy: Season 14,2000000,2024-01-01,2024-06-30
2337,19.0,Grey's Anatomy: Season 19,2000000,2024-01-01,2024-06-30
2339,15.0,Grey's Anatomy: Season 15,1900000,2024-01-01,2024-06-30
2341,16.0,Grey's Anatomy: Season 16,1800000,2024-01-01,2024-06-30
2343,18.0,Grey's Anatomy: Season 18,1700000,2024-01-01,2024-06-30
2345,17.0,Grey's Anatomy: Season 17,1700000,2024-01-01,2024-06-30
2347,20.0,Grey's Anatomy: Season 20,100000,2024-01-01,2024-06-30

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [17]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/Colab Notebooks/MNA/TC5053 - Ciencia y analítica de datos/Actividad3_BD_Manipulacion"
os.chdir(DIR)

In [20]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [21]:
# Leer EMPLOYEE
docs = db.collection('EMPLOYEE').stream()

employees = []

for doc in docs:
    employee = doc.to_dict()
    employee['id'] = doc.id
    employees.append(employee)

# Crear DataFrame
employee_df = pd.DataFrame(employees)

employee_df

  emp_fname   emp_lname                    id              emp_hiredate
0     David      Senior  8LcLuxVHGAd2d9IQc5jF 1989-07-12 06:00:00+00:00
1   William  Smithfield  Fzd60D6Z2CU4n0wVV8YN 2004-06-04 05:00:00+00:00
2      John        News  lX5xuQ5w3i6ib2ExccWY 2000-11-08 06:00:00+00:00
3      June     Arbough  yocFj2lichOkbAj9NBfp 1996-12-01 06:00:00+00:00

In [22]:
firebase_admin.delete_app(firebase_admin.get_app())

---

**Declaración de uso de IA**

*   OpenAI. (2026). *ChatGPT (basado en GPT-4)* GPT-5.6 Luna, utilizado para generación de código y depuración. https://chat.openai.com/

---